name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/checkout@v2
      with:
        repository: kijanac/manage-py
        path: manage

    - name: Update conda
      run: conda update -n base -c defaults conda

    - name: Make conda environment and install dependencies
      run: $(conda info --base)/bin/python3 manage/manage.py setup dev

    - name: Lint code
      run: conda run -n dev python manage/manage.py lint

    - name: Install package (editable)
      run: conda run -n dev python manage/manage.py install

    - name: Run tests on editable install
      run: conda run -n dev python manage/manage.py test
