name: Deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update conda
      run: conda update -n base -c defaults conda

    - name: Make conda environment and install dependencies
      run: $(conda info --base)/bin/python3 manage.py setup dev

    - name: Lint code
      run: conda run -n dev python manage.py lint

    - name: Install package (editable)
      run: conda run -n dev python manage.py install

    - name: Run tests on editable install
      run: conda run -n dev python manage.py test ${{ secrets.CODECOV_TOKEN }}

    - name: Build sdist and wheel
      run: conda run -n dev python manage.py build

    - name: Build conda package
      run: conda run -n dev python manage.py build_conda

    - name: Deploy to PyPI and Anaconda
      run: conda run -n dev python manage.py publish ${{ secrets.PYPI_TOKEN }} ${{ secrets.CONDA_TOKEN }}
